# SPDX-FileCopyrightText: 2026 Apanazar
#
# SPDX-License-Identifier: CC-BY-4.0

name: REUSE

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  reuse:
    uses: SmoothTeam/.github/.github/workflows/reuse.yml@main
